import type { Metadata } from "next";
import { Space_Grotesk, Inter } from "next/font/google";
import "../globals.css";
import NavBar from "../components/NavBar";



const spaceGroteck = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"]
})

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGroteck.variable} ${inter.variable} antialiased`}
      >
          <NavBar />
          {children}
      </body>
    </html>
  );
}
