import type { Metadata } from "next";
import { Space_Grotesk, Inter } from "next/font/google";
import "../globals.css";
import NavBar from "../components/NavBar";



const spaceGroteck = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"]
})

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body
        className={`${spaceGroteck.variable} ${inter.variable} antialiased`}
      >
        <main className="container-main-page">
          <NavBar />
          {children}
        </main>
      </body>
    </html>
  );
}
